// services/mockData.ts
import { User, UserRole, KYCStatus, Project, ProjectStatus, Wallet, Transaction, TransactionType, Investment, Report, ReportStatus, Service, ServiceRequest, ServiceStatus, WithdrawalRequest, WithdrawalStatus, MilestoneStatus, ProjectStage } from '../types';

// USERS
export let mockUsers: User[] = [
  {
    id: 'usr_admin1',
    firstName: 'Admin',
    lastName: 'InvestMaroc',
    email: 'admin@investmaroc.com',
    role: UserRole.SUPER_ADMIN,
    phone: '+212600000000',
    phoneVerified: true,
    kycStatus: KYCStatus.VERIFIED,
    createdAt: new Date('2023-01-01'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_admin1',
  },
  {
    id: 'usr_inv1',
    firstName: 'Ahmed',
    lastName: 'El Fassi',
    email: 'ahmed@investor.com',
    role: UserRole.INVESTOR,
    phone: '+212611111111',
    phoneVerified: true,
    kycStatus: KYCStatus.VERIFIED,
    createdAt: new Date('2023-02-15'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_inv1',
    bio: 'Investisseur passionné par les technologies vertes.',
    city: 'Rabat',
    address: '123 Avenue Hassan II',
    bankInfo: {
      rib: '123456789012345678901234',
      bankName: 'Attijariwafa Bank'
    }
  },
  {
    id: 'usr_inv2',
    firstName: 'Fatima',
    lastName: 'Zahra',
    email: 'fatima@investor.com',
    role: UserRole.INVESTOR,
    phone: '+212622222222',
    phoneVerified: true,
    kycStatus: KYCStatus.PENDING,
    createdAt: new Date('2023-03-20'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_inv2',
    bio: 'Je cherche à diversifier mon portefeuille.',
    city: 'Marrakech',
    address: '456 Rue de la Kasbah',
  },
  {
    id: 'usr_po1',
    firstName: 'Youssef',
    lastName: 'Alaoui',
    email: 'youssef@owner.com',
    role: UserRole.PROJECT_OWNER,
    phone: '+212633333333',
    phoneVerified: true,
    kycStatus: KYCStatus.VERIFIED,
    createdAt: new Date('2024-04-01'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_po1',
    bio: 'Entrepreneur en série dans le domaine de la restauration.',
    city: 'Casablanca',
    address: '789 Boulevard Anfa',
  },
  {
    id: 'usr_po2',
    firstName: 'Khadija',
    lastName: 'Bennani',
    email: 'khadija@owner.com',
    role: UserRole.PROJECT_OWNER,
    phone: '+212644444444',
    phoneVerified: true,
    kycStatus: KYCStatus.PENDING,
    createdAt: new Date('2023-05-10'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_po2',
    bio: 'Jeune diplômée avec un projet innovant en agriculture.',
    city: 'Fès',
    address: '101 Derb Lihoudi',
  },
  // --- NOUVEAUX UTILISATEURS FACTICES ---
  {
    id: 'usr_admin2',
    firstName: 'Leila',
    lastName: 'Alaoui',
    email: 'leila.admin@investmaroc.com',
    role: UserRole.VALIDATOR_ADMIN,
    phone: '+212600000001',
    phoneVerified: true,
    kycStatus: KYCStatus.VERIFIED,
    createdAt: new Date('2023-01-02'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_admin2',
  },
  {
    id: 'usr_admin3',
    firstName: 'Karim',
    lastName: 'Saadi',
    email: 'karim.finance@investmaroc.com',
    role: UserRole.FINANCIAL_ADMIN,
    phone: '+212600000002',
    phoneVerified: true,
    kycStatus: KYCStatus.VERIFIED,
    createdAt: new Date('2023-01-03'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_admin3',
  },
  {
    id: 'usr_admin4',
    firstName: 'Nadia',
    lastName: 'Chafik',
    email: 'nadia.services@investmaroc.com',
    role: UserRole.SERVICE_ADMIN,
    phone: '+212600000003',
    phoneVerified: true,
    kycStatus: KYCStatus.VERIFIED,
    createdAt: new Date('2023-01-04'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_admin4',
  },
  {
    id: 'usr_inv3',
    firstName: 'Amine',
    lastName: 'Berrada',
    email: 'amine@investor.com',
    role: UserRole.INVESTOR,
    phone: '+212655555555',
    phoneVerified: true,
    kycStatus: KYCStatus.VERIFIED,
    createdAt: new Date('2023-06-12'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_inv3',
    bio: 'Investisseur ange spécialisé dans la FinTech et le SaaS.',
    city: 'Casablanca',
    address: '10 Appt 5, Boulevard Zerktouni',
  },
  {
    id: 'usr_po3',
    firstName: 'Sofia',
    lastName: 'Tazi',
    email: 'sofia@owner.com',
    role: UserRole.PROJECT_OWNER,
    phone: '+212666666666',
    phoneVerified: true,
    kycStatus: KYCStatus.VERIFIED,
    createdAt: new Date('2023-07-22'),
    profilePictureUrl: 'https://i.pravatar.cc/150?u=usr_po3',
    bio: 'Créatrice de mode, je lance une marque de prêt-à-porter éco-responsable.',
    city: 'Marrakech',
    address: '25 Rue de la Liberté, Guéliz',
  },
];

// PROJECTS
export let mockProjects: Project[] = [
  {
    id: 'prj_1',
    title: { fr: 'Restaurant de Fusion à Casablanca', ar: 'مطعم فيوجن في الدار البيضاء' },
    description: { fr: 'Un concept unique de restaurant qui fusionne la cuisine marocaine traditionnelle avec des saveurs asiatiques modernes. Situé au cœur du quartier Maârif, ce projet vise à devenir une destination culinaire incontournable.', ar: 'مفهوم فريد لمطعم يدمج المطبخ المغربي التقليدي مع النكهات الآسيوية الحديثة. يقع في قلب حي المعاريف، ويهدف هذا المشروع إلى أن يصبح وجهة طهي لا غنى عنها.' },
    category: 'Restauration',
    location: 'Casablanca',
    fundingGoal: 500000,
    currentFunding: 275000,
    startDate: new Date('2024-05-01'),
    deadline: new Date('2024-08-30'),
    minimumInvestment: 5000,
    equityOffered: 20,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[3], // Youssef Alaoui
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
    roadmap: [
      {
        id: 'rm_1_1',
        title: { fr: 'Obtention des licences', ar: 'الحصول على التراخيص' },
        description: { fr: 'Finalisation de toutes les formalités administratives et obtention des permis nécessaires pour l\'ouverture.', ar: 'استكمال كافة الإجراءات الإدارية والحصول على التراخيص اللازمة للافتتاح.' },
        targetDate: new Date('2024-05-20'),
        status: MilestoneStatus.COMPLETED,
      },
      {
        id: 'rm_1_2',
        title: { fr: 'Rénovation du local', ar: 'تجديد المحل' },
        description: { fr: 'Travaux de rénovation et aménagement intérieur du restaurant selon le design validé.', ar: 'أعمال التجديد والتصميم الداخلي للمطعم حسب التصميم المعتمد.' },
        targetDate: new Date('2024-07-15'),
        status: MilestoneStatus.IN_PROGRESS,
      },
      {
        id: 'rm_1_3',
        title: { fr: 'Recrutement de l\'équipe', ar: 'توظيف الفريق' },
        description: { fr: 'Recrutement du chef de cuisine, des serveurs et du personnel de salle.', ar: 'توظيف رئيس الطهاة والنادلين وموظفي القاعة.' },
        targetDate: new Date('2024-08-01'),
        status: MilestoneStatus.NOT_STARTED,
      },
      {
        id: 'rm_1_4',
        title: { fr: 'Lancement et inauguration', ar: 'الإطلاق والافتتاح' },
        description: { fr: 'Soirée d\'inauguration officielle et ouverture au public.', ar: 'حفل الافتتاح الرسمي والفتح للجمهور.' },
        targetDate: new Date('2024-08-25'),
        status: MilestoneStatus.NOT_STARTED,
      },
    ],
  },
  {
    id: 'prj_2',
    title: { fr: 'Ferme Verticale Bio à Agadir', ar: 'مزرعة عمودية عضوية في أغادير' },
    description: { fr: "Projet d'agriculture urbaine utilisant des techniques de culture verticale pour produire des légumes bio sans pesticides, destinés au marché local et aux restaurants.", ar: 'مشروع زراعة حضرية يستخدم تقنيات الزراعة العمودية لإنتاج خضروات عضوية خالية من المبيدات، موجهة للسوق المحلي والمطاعم.' },
    category: 'Agriculture',
    location: 'Agadir',
    fundingGoal: 800000,
    currentFunding: 225000,
    startDate: new Date('2024-06-15'),
    deadline: new Date('2024-09-30'),
    minimumInvestment: 10000,
    equityOffered: 25,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4], // Khadija Bennani
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_3',
    title: { fr: 'Plateforme E-learning "Dorouss"', ar: 'منصة التعليم الإلكتروني "دروس"' },
    description: { fr: 'Une plateforme en ligne pour le soutien scolaire, offrant des cours interactifs et des exercices pour les élèves du primaire au lycée au Maroc.', ar: 'منصة إلكترونية للدعم المدرسي، تقدم دروسًا تفاعلية وتمارين للتلاميذ من الابتدائي إلى الثانوي في المغرب.' },
    category: 'Technologie',
    location: 'Rabat',
    fundingGoal: 300000,
    currentFunding: 300000,
    startDate: new Date('2024-03-01'),
    deadline: new Date('2024-06-01'),
    minimumInvestment: 2500,
    equityOffered: 15,
    status: ProjectStatus.FUNDED,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
    financials: [
      { year: 2022, revenue: 450000, profit: 80000 },
      { year: 2023, revenue: 780000, profit: 150000 },
    ]
  },
  {
    id: 'prj_4',
    title: { fr: 'Concept Store Artisanal à Marrakech', ar: 'متجر مبتكر للحرف اليدوية في مراكش' },
    description: { fr: "Boutique valorisant l'artisanat marocain revisité par de jeunes designers. Le projet inclut un espace café et des ateliers.", ar: 'متجر يعرض الحرف اليدوية المغربية بلمسة عصرية من تصميم شباب. يتضمن المشروع مقهى وورش عمل.' },
    category: 'Artisanat',
    location: 'Marrakech',
    fundingGoal: 400000,
    currentFunding: 50000,
    startDate: new Date('2024-07-01'),
    deadline: new Date('2024-08-01'),
    minimumInvestment: 5000,
    equityOffered: 30,
    status: ProjectStatus.FAILED,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1563852423149-993f35a909a3?q=80&w=1932&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
    {
    id: 'prj_5',
    title: { fr: 'Application Mobile de Co-voiturage', ar: 'تطبيق جوال لمشاركة السيارات' },
    description: { fr: "Développement d'une application mobile sécurisée pour le co-voiturage inter-villes au Maroc.", ar: 'تطوير تطبيق جوال آمن لمشاركة السيارات بين المدن في المغرب.' },
    category: 'Technologie',
    location: 'Tout le Maroc',
    fundingGoal: 600000,
    currentFunding: 120000,
    startDate: new Date('2024-08-01'),
    deadline: new Date('2024-11-01'),
    minimumInvestment: 7500,
    equityOffered: 22,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=2070&auto=format&fit=crop',
  },
   {
    id: 'prj_6',
    title: { fr: 'Café-Lounge à Tanger', ar: 'مقهى واستراحة في طنجة' },
    description: { fr: 'Un café moderne avec vue sur la mer, offrant des produits locaux et un espace de co-working.', ar: 'مقهى عصري يطل على البحر، يقدم منتجات محلية ومساحة للعمل المشترك.' },
    category: 'Restauration',
    location: 'Tanger',
    fundingGoal: 350000,
    currentFunding: 350000,
    startDate: new Date('2024-02-01'),
    deadline: new Date('2024-05-01'),
    minimumInvestment: 5000,
    equityOffered: 18,
    status: ProjectStatus.COMPLETED,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[3], // Youssef Alaoui
    imageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
    financials: [
      { year: 2022, revenue: 950000, profit: 220000 },
      { year: 2023, revenue: 1300000, profit: 310000 },
    ]
  },
  {
    id: 'prj_7',
    title: { fr: 'Marque de Mode Éco-responsable "Sofia Tazi"', ar: 'علامة أزياء صديقة للبيئة "صوفيا التازي"' },
    description: { fr: 'Lancement d\'une nouvelle marque de prêt-à-porter pour femmes, axée sur des matériaux durables et une production éthique. La première collection sera inspirée par l\'artisanat marocain avec une touche moderne.', ar: 'إطلاق علامة تجارية جديدة للملابس الجاهزة النسائية، تركز على المواد المستدامة والإنتاج الأخلاقي. ستكون المجموعة الأولى مستوحاة من الحرف اليدوية المغربية بلمسة عصرية.' },
    category: 'Mode',
    location: 'Marrakech',
    fundingGoal: 450000,
    currentFunding: 0,
    startDate: new Date('2024-09-01'),
    deadline: new Date('2024-12-01'),
    minimumInvestment: 5000,
    equityOffered: 35,
    status: ProjectStatus.PENDING_APPROVAL,
    stage: ProjectStage.IDEA,
    owner: mockUsers[8], // Sofia Tazi
    imageUrl: 'https://images.unsplash.com/photo-1551803091-e373c2c5075f?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin2', // Leila Alaoui
  },
  {
    id: 'prj_8',
    title: { fr: "Boulangerie Pâtisserie Française à Rabat", ar: "مخبزة وحلويات فرنسية في الرباط" },
    description: { fr: "Une boulangerie-pâtisserie artisanale offrant des produits français authentiques dans le quartier de l'Agdal.", ar: "مخبزة وحلويات حرفية تقدم منتجات فرنسية أصيلة في حي أكدال." },
    category: 'Restauration',
    location: 'Rabat',
    fundingGoal: 400000,
    currentFunding: 150000,
    startDate: new Date('2024-07-10'),
    deadline: new Date('2024-10-10'),
    minimumInvestment: 4000,
    equityOffered: 20,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1568254183919-78a4f43a2877?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_9',
    title: { fr: "Food Truck de Tacos à Marrakech", ar: "شاحنة طعام تاكو في مراكش" },
    description: { fr: "Un camion de cuisine de rue spécialisé dans les tacos mexicains avec une touche marocaine, ciblant les zones touristiques et les événements.", ar: "شاحنة طعام شارع متخصصة في التاكو المكسيكي بلمسة مغربية، تستهدف المناطق السياحية والمناسبات." },
    category: 'Restauration',
    location: 'Marrakech',
    fundingGoal: 200000,
    currentFunding: 80000,
    startDate: new Date('2024-06-25'),
    deadline: new Date('2024-09-25'),
    minimumInvestment: 2000,
    equityOffered: 25,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[8],
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-151f1a6c6c44?q=80&w=1986&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_10',
    title: { fr: "Bar à Jus & Salades Healthy à Agadir", ar: "بار عصائر وسلطات صحية في أغادير" },
    description: { fr: "Un espace dédié à une alimentation saine, proposant des jus frais, des smoothies et des salades gourmandes pour les touristes et les locaux.", ar: "مساحة مخصصة للطعام الصحي، تقدم عصائر طازجة، وعصائر السموثي، وسلطات شهية للسياح والسكان المحليين." },
    category: 'Restauration',
    location: 'Agadir',
    fundingGoal: 250000,
    currentFunding: 175000,
    startDate: new Date('2024-07-01'),
    deadline: new Date('2024-09-01'),
    minimumInvestment: 2500,
    equityOffered: 20,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1601599561213-832382fd07ba?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_11',
    title: { fr: "Restaurant Italien Authentique à Fès", ar: "مطعم إيطالي أصيل في فاس" },
    description: { fr: "Importation du savoir-faire italien dans la médina de Fès, avec des pâtes fraîches faites maison et des pizzas cuites au feu de bois.", ar: "استيراد الخبرة الإيطالية إلى مدينة فاس القديمة، مع معكرونة طازجة مصنوعة منزليًا وبيتزا مطبوخة في فرن الحطب." },
    category: 'Restauration',
    location: 'Fès',
    fundingGoal: 550000,
    currentFunding: 120000,
    startDate: new Date('2024-08-15'),
    deadline: new Date('2024-11-15'),
    minimumInvestment: 5000,
    equityOffered: 25,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_12',
    title: { fr: "Dark Kitchen pour Livraison à Casablanca", ar: "مطبخ سحابي للتوصيل في الدار البيضاء" },
    description: { fr: "Cuisine fantôme optimisée pour la livraison, proposant plusieurs marques virtuelles (Burger, Pizza, Asiatique) depuis un seul emplacement.", ar: "مطبخ سحابي محسن للتوصيل، يقدم علامات تجارية افتراضية متعددة (برجر، بيتزا، آسيوي) من موقع واحد." },
    category: 'Restauration',
    location: 'Casablanca',
    fundingGoal: 700000,
    currentFunding: 450000,
    startDate: new Date('2024-05-20'),
    deadline: new Date('2024-08-20'),
    minimumInvestment: 10000,
    equityOffered: 30,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1581349439371-a0d8e1975b34?q=80&w=1964&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
    financials: [
      { year: 2023, revenue: 1200000, profit: 180000 },
    ]
  },
   {
    id: 'prj_13',
    title: { fr: "Glacier Artisanal à Essaouira", ar: "محل آيس كريم حرفي في الصويرة" },
    description: { fr: "Production de glaces et sorbets artisanaux à base de fruits locaux et d'ingrédients de haute qualité.", ar: "إنتاج آيس كريم وسوربيه حرفي باستخدام الفواكه المحلية والمكونات عالية الجودة." },
    category: 'Restauration',
    location: 'Essaouira',
    fundingGoal: 300000,
    currentFunding: 30000,
    startDate: new Date('2024-07-20'),
    deadline: new Date('2024-09-20'),
    minimumInvestment: 3000,
    equityOffered: 20,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[8],
    imageUrl: 'https://images.unsplash.com/photo-1567197786948-c89b768a483a?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_14',
    title: { fr: "Salon de Thé de Luxe à Ifrane", ar: "صالون شاي فاخر في إفران" },
    description: { fr: "Un concept de salon de thé haut de gamme, proposant une sélection de thés du monde et de pâtisseries fines dans un cadre élégant.", ar: "مفهوم صالون شاي راقٍ، يقدم مجموعة مختارة من أنواع الشاي العالمية والحلويات الفاخرة في أجواء أنيقة." },
    category: 'Restauration',
    location: 'Ifrane',
    fundingGoal: 450000,
    currentFunding: 200000,
    startDate: new Date('2024-09-01'),
    deadline: new Date('2024-12-01'),
    minimumInvestment: 5000,
    equityOffered: 25,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1559925239-a9a7a1394b32?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_15',
    title: { fr: "Restaurant de Fruits de Mer à Dakhla", ar: "مطعم مأكولات بحرية في الداخلة" },
    description: { fr: "Restaurant spécialisé dans les produits de la mer frais, avec une vue imprenable sur la lagune de Dakhla.", ar: "مطعم متخصص في المأكولات البحرية الطازجة، مع إطلالة خلابة على بحيرة الداخلة." },
    category: 'Restauration',
    location: 'Dakhla',
    fundingGoal: 650000,
    currentFunding: 150000,
    startDate: new Date('2024-10-01'),
    deadline: new Date('2025-01-01'),
    minimumInvestment: 10000,
    equityOffered: 30,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1541544458-44242699b803?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_16',
    title: { fr: "Marketplace pour Artisans Marocains", ar: "سوق إلكتروني للحرفيين المغاربة" },
    description: { fr: "Une plateforme en ligne pour connecter les artisans marocains directement avec des clients du monde entier.", ar: "منصة إلكترونية لربط الحرفيين المغاربة مباشرة بالعملاء من جميع أنحاء العالم." },
    category: 'Technologie',
    location: 'En ligne',
    fundingGoal: 400000,
    currentFunding: 200000,
    startDate: new Date('2024-07-01'),
    deadline: new Date('2024-10-01'),
    minimumInvestment: 5000,
    equityOffered: 20,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[8],
    imageUrl: 'https://images.unsplash.com/photo-1542345627-9a8508332168?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_17',
    title: { fr: "App de Réservation Sportive 'Mلاعب'", ar: "تطبيق حجز رياضي 'ملاعب'" },
    description: { fr: "Application mobile pour réserver des terrains de sport (foot, paddle, tennis) et trouver des partenaires de jeu.", ar: "تطبيق جوال لحجز الملاعب الرياضية (كرة القدم، البادل، التنس) والعثور على شركاء للعب." },
    category: 'Technologie',
    location: 'National',
    fundingGoal: 500000,
    currentFunding: 100000,
    startDate: new Date('2024-06-15'),
    deadline: new Date('2024-09-15'),
    minimumInvestment: 5000,
    equityOffered: 18,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1565982242194-3a7a993a4049?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_18',
    title: { fr: "Solution SaaS de Gestion pour PME", ar: "حل SaaS لإدارة الشركات الصغيرة والمتوسطة" },
    description: { fr: "Un logiciel en tant que service (SaaS) pour aider les PME marocaines à gérer leur facturation, leur inventaire et leurs relations clients.", ar: "برنامج كخدمة (SaaS) لمساعدة الشركات الصغيرة والمتوسطة المغربية على إدارة الفواتير والمخزون وعلاقات العملاء." },
    category: 'Technologie',
    location: 'En ligne',
    fundingGoal: 800000,
    currentFunding: 350000,
    startDate: new Date('2024-05-10'),
    deadline: new Date('2024-08-10'),
    minimumInvestment: 15000,
    equityOffered: 25,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
    financials: [
      { year: 2023, revenue: 1500000, profit: 400000 },
    ]
  },
   {
    id: 'prj_19',
    title: { fr: "Jeu Mobile Éducatif 'Tarikhona'", ar: "لعبة جوال تعليمية 'تاريخنا'" },
    description: { fr: "Un jeu mobile interactif qui enseigne l'histoire du Maroc aux enfants de manière ludique et engageante.", ar: "لعبة جوال تفاعلية تعلم تاريخ المغرب للأطفال بطريقة ممتعة وجذابة." },
    category: 'Technologie',
    location: 'Mobile',
    fundingGoal: 250000,
    currentFunding: 25000,
    startDate: new Date('2024-08-01'),
    deadline: new Date('2024-11-01'),
    minimumInvestment: 2000,
    equityOffered: 15,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[8],
    imageUrl: 'https://images.unsplash.com/photo-1589400406399-594318c3d908?q=80&w=1965&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
   {
    id: 'prj_20',
    title: { fr: "Agence de Marketing Digital IA", ar: "وكالة تسويق رقمي بالذكاء الاصطناعي" },
    description: { fr: "Une agence utilisant l'intelligence artificielle pour optimiser les campagnes publicitaires en ligne pour les entreprises marocaines.", ar: "وكالة تستخدم الذكاء الاصطناعي لتحسين الحملات الإعلانية عبر الإنترنت للشركات المغربية." },
    category: 'Technologie',
    location: 'Casablanca',
    fundingGoal: 350000,
    currentFunding: 150000,
    startDate: new Date('2024-07-20'),
    deadline: new Date('2024-10-20'),
    minimumInvestment: 5000,
    equityOffered: 20,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-95fc6ihk23ba4?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_21',
    title: { fr: "Plateforme de Télémédecine", ar: "منصة التطبيب عن بعد" },
    description: { fr: "Mise en relation de patients avec des médecins pour des consultations vidéo, prescriptions en ligne et suivi médical à distance.", ar: "ربط المرضى بالأطباء للاستشارات عبر الفيديو والوصفات الطبية عبر الإنترنت والمتابعة الطبية عن بعد." },
    category: 'Technologie',
    location: 'National',
    fundingGoal: 1200000,
    currentFunding: 400000,
    startDate: new Date('2024-09-01'),
    deadline: new Date('2025-01-01'),
    minimumInvestment: 20000,
    equityOffered: 28,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d27bfb?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_22',
    title: { fr: "FinTech de Micro-crédit", ar: "شركة تكنولوجيا مالية للقروض الصغيرة" },
    description: { fr: "Application mobile offrant des micro-crédits rapides et accessibles aux petites entreprises et aux entrepreneurs non bancarisés.", ar: "تطبيق جوال يقدم قروضًا صغيرة سريعة ومتاحة للشركات الصغيرة ورجال الأعمال غير المتعاملين مع البنوك." },
    category: 'Technologie',
    location: 'En ligne',
    fundingGoal: 2000000,
    currentFunding: 500000,
    startDate: new Date('2024-10-01'),
    deadline: new Date('2025-02-01'),
    minimumInvestment: 25000,
    equityOffered: 30,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[3],
    imageUrl: 'https://images.unsplash.com/photo-1601597111158-2f954202b3cb?q=80&w=1964&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_23',
    title: { fr: "Start-up de Cybersécurité", ar: "شركة ناشئة في مجال الأمن السيبراني" },
    description: { fr: "Fourniture de services de cybersécurité, y compris des audits de sécurité et des solutions de protection pour les entreprises marocaines.", ar: "توفير خدمات الأمن السيبراني، بما في ذلك تدقيق الأمان وحلول الحماية للشركات المغربية." },
    category: 'Technologie',
    location: 'Rabat',
    fundingGoal: 900000,
    currentFunding: 150000,
    startDate: new Date('2024-08-20'),
    deadline: new Date('2024-11-20'),
    minimumInvestment: 10000,
    equityOffered: 25,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[8],
    imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_24',
    title: { fr: "Culture hydroponique de fraises", ar: "زراعة الفراولة المائية" },
    description: { fr: "Production de fraises de haute qualité toute l'année en utilisant des systèmes hydroponiques économes en eau.", ar: "إنتاج فراولة عالية الجودة على مدار العام باستخدام أنظمة الزراعة المائية الموفرة للمياه." },
    category: 'Agriculture',
    location: 'Région de Souss-Massa',
    fundingGoal: 750000,
    currentFunding: 300000,
    startDate: new Date('2024-07-15'),
    deadline: new Date('2024-10-15'),
    minimumInvestment: 10000,
    equityOffered: 22,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1587393855524-7ab4376c52a0?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_25',
    title: { fr: "Production d'huile d'argan bio", ar: "إنتاج زيت الأركان العضوي" },
    description: { fr: "Création d'une coopérative moderne pour la production et l'exportation d'huile d'argan certifiée biologique.", ar: "إنشاء تعاونية حديثة لإنتاج وتصدير زيت الأركان العضوي المعتمد." },
    category: 'Agriculture',
    location: 'Essaouira',
    fundingGoal: 600000,
    currentFunding: 450000,
    startDate: new Date('2024-04-01'),
    deadline: new Date('2024-08-01'),
    minimumInvestment: 8000,
    equityOffered: 18,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1598555769074-891ded10996b?q=80&w=1964&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_26',
    title: { fr: "Élevage de volailles en plein air", ar: "تربية الدواجن في الهواء الطلق" },
    description: { fr: "Ferme d'élevage de poulets en plein air, axée sur le bien-être animal et la production d'œufs et de viande de qualité supérieure.", ar: "مزرعة لتربية الدجاج في الهواء الطلق، تركز على رفاهية الحيوان وإنتاج بيض ولحوم عالية الجودة." },
    category: 'Agriculture',
    location: 'Béni Mellal',
    fundingGoal: 500000,
    currentFunding: 100000,
    startDate: new Date('2024-08-01'),
    deadline: new Date('2024-11-01'),
    minimumInvestment: 5000,
    equityOffered: 20,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1588649983550-24a181b894c7?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_27',
    title: { fr: "Apiculture et production de miel", ar: "تربية النحل وإنتاج العسل" },
    description: { fr: "Installation de ruches dans des zones préservées pour produire différents types de miel marocain (eucalyptus, oranger, thym).", ar: "تركيب خلايا النحل في مناطق محمية لإنتاج أنواع مختلفة من العسل المغربي (الكالبتوس، البرتقال، الزعتر)." },
    category: 'Agriculture',
    location: 'Région de Tadla-Azilal',
    fundingGoal: 300000,
    currentFunding: 180000,
    startDate: new Date('2024-05-15'),
    deadline: new Date('2024-08-15'),
    minimumInvestment: 3000,
    equityOffered: 15,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1587334274328-64186a80aeee?q=80&w=2071&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_28',
    title: { fr: "Ferme aquaponique", ar: "مزرعة أكوابونيك" },
    description: { fr: "Système intégré combinant l'élevage de poissons et la culture de plantes, créant un écosystème durable et productif.", ar: "نظام متكامل يجمع بين تربية الأسماك وزراعة النباتات، مما يخلق نظامًا بيئيًا مستدامًا ومنتجًا." },
    category: 'Agriculture',
    location: 'Kenitra',
    fundingGoal: 900000,
    currentFunding: 250000,
    startDate: new Date('2024-09-10'),
    deadline: new Date('2024-12-10'),
    minimumInvestment: 12000,
    equityOffered: 28,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1599395252815-460d37e69830?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
   {
    id: 'prj_29',
    title: { fr: "Production de safran à Taliouine", ar: "إنتاج الزعفران في تالوين" },
    description: { fr: "Culture et commercialisation du safran de Taliouine, l'or rouge du Maroc, en respectant les méthodes traditionnelles.", ar: "زراعة وتسويق زعفران تالوين، الذهب الأحمر للمغرب، مع احترام الطرق التقليدية." },
    category: 'Agriculture',
    location: 'Taliouine',
    fundingGoal: 400000,
    currentFunding: 400000,
    startDate: new Date('2024-01-01'),
    deadline: new Date('2024-05-01'),
    minimumInvestment: 5000,
    equityOffered: 20,
    status: ProjectStatus.FUNDED,
    stage: ProjectStage.GROWTH,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1568402487983-885446059737?q=80&w=2070&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_30',
    title: { fr: "Verger d'avocatiers pour l'export", ar: "بستان أفوكادو للتصدير" },
    description: { fr: "Plantation et entretien d'un verger d'avocatiers destiné principalement à l'exportation vers le marché européen.", ar: "زراعة وصيانة بستان أفوكادو مخصص بشكل أساسي للتصدير إلى السوق الأوروبية." },
    category: 'Agriculture',
    location: 'Gharb',
    fundingGoal: 1500000,
    currentFunding: 600000,
    startDate: new Date('2024-06-01'),
    deadline: new Date('2024-10-01'),
    minimumInvestment: 25000,
    equityOffered: 35,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1616010953934-2b638b2b5b31?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
  {
    id: 'prj_31',
    title: { fr: "Unité de compostage industriel", ar: "وحدة تسميد صناعي" },
    description: { fr: "Transformation des déchets organiques en compost de haute qualité pour l'agriculture biologique.", ar: "تحويل النفايات العضوية إلى سماد عالي الجودة للزراعة العضوية." },
    category: 'Agriculture',
    location: 'Settat',
    fundingGoal: 700000,
    currentFunding: 150000,
    startDate: new Date('2024-07-01'),
    deadline: new Date('2024-10-01'),
    minimumInvestment: 8000,
    equityOffered: 22,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1587883984101-20998f58d975?q=80&w=1974&auto=format&fit=crop',
    supervisorId: 'usr_admin1',
  },
  {
    id: 'prj_32',
    title: { fr: "Culture de champignons de Paris", ar: "زراعة فطر باريس" },
    description: { fr: "Mise en place d'une champignonnière moderne pour approvisionner le marché national en champignons frais.", ar: "إنشاء مزرعة فطر حديثة لتزويد السوق الوطني بالفطر الطازج." },
    category: 'Agriculture',
    location: 'Meknès',
    fundingGoal: 450000,
    currentFunding: 20000,
    startDate: new Date('2024-09-01'),
    deadline: new Date('2024-12-01'),
    minimumInvestment: 5000,
    equityOffered: 20,
    status: ProjectStatus.ACTIVE,
    stage: ProjectStage.IDEA,
    owner: mockUsers[4],
    imageUrl: 'https://images.unsplash.com/photo-1594292135541-69436214f7ae?q=80&w=1968&auto=format&fit=crop',
    supervisorId: 'usr_admin2',
  },
];

// WALLETS
export let mockWallets: Wallet[] = [
  {
    id: 'wlt_inv1',
    userId: 'usr_inv1',
    balance: 50000,
  },
  {
    id: 'wlt_inv2',
    userId: 'usr_inv2',
    balance: 10000,
  },
  {
    id: 'wlt_inv3',
    userId: 'usr_inv3',
    balance: 175000, // Updated from 250000 after investment
  },
];

// TRANSACTIONS
export let mockTransactions: Transaction[] = [
  {
    id: 'trn_1',
    walletId: 'wlt_inv1',
    type: TransactionType.DEPOSIT,
    amount: 75000,
    description: 'Dépôt par carte bancaire',
    date: new Date('2024-05-05'),
    status: 'Completed',
  },
  {
    id: 'trn_2',
    walletId: 'wlt_inv1',
    type: TransactionType.INVESTMENT,
    amount: 25000,
    description: 'Investissement dans: Restaurant de Fusion à Casablanca',
    date: new Date('2024-05-10'),
    status: 'Completed',
  },
  {
    id: 'trn_3',
    walletId: 'wlt_inv3',
    type: TransactionType.INVESTMENT,
    amount: 75000,
    description: 'Investissement dans: Ferme Verticale Bio à Agadir',
    date: new Date('2024-06-20'),
    status: 'Completed',
  },
];

// INVESTMENTS
export let mockInvestments: Investment[] = [
  {
    id: 'inv_1',
    userId: 'usr_inv1',
    projectId: 'prj_1',
    amount: 25000,
    date: new Date('2024-05-10'),
  },
  {
    id: 'inv_2',
    userId: 'usr_inv3', // Amine Berrada
    projectId: 'prj_2',
    amount: 75000,
    date: new Date('2024-06-20'),
  },
];

// REPORTS
export let mockReports: Report[] = [
  {
    id: 'rep_1',
    projectId: 'prj_1',
    title: 'Rapport d\'avancement - Semaine 1',
    content: 'Les travaux de rénovation de la cuisine ont commencé. Le gros œuvre est terminé et nous allons attaquer la plomberie la semaine prochaine. Ci-joint le rapport détaillé avec des photos.',
    fileName: 'Rapport_S1_Cuisine.pdf',
    fileType: 'application/pdf',
    submittedAt: new Date('2024-06-10'),
    status: ReportStatus.PUBLISHED,
    publishedAt: new Date('2024-06-11'),
  },
  {
    id: 'rep_2',
    projectId: 'prj_1',
    title: 'Mise à jour financière - Juin 2024',
    content: 'Le budget est respecté. Nous avons négocié de bons tarifs avec nos fournisseurs de matières premières. Le détail des dépenses est disponible dans le document attaché.',
    fileName: 'Budget_Juin_2024.xlsx',
    fileType: 'application/vnd.ms-excel',
    submittedAt: new Date('2024-07-05'),
    status: ReportStatus.PENDING,
  },
  {
    id: 'rep_3',
    projectId: 'prj_2',
    title: 'Installation des systèmes hydroponiques',
    content: 'L\'installation des systèmes de culture verticale est terminée à 80%. Nous attendons la livraison des dernières pompes pour finaliser. Les premiers semis sont prévus pour le 15 du mois prochain.',
    fileName: 'Photos_Installation.zip',
    fileType: 'application/zip',
    submittedAt: new Date('2024-07-02'),
    status: ReportStatus.PENDING,
  },
];

// PROFESSIONAL SERVICES
export let mockServices: Service[] = [
  {
    id: 'serv_1',
    title: { fr: 'Rédaction de Business Plan', ar: 'صياغة خطة عمل' },
    description: {
      fr: 'Un service complet pour rédiger un business plan professionnel et convaincant, incluant études de marché, prévisions financières et stratégie marketing. Essentiel pour présenter votre projet aux investisseurs.',
      ar: 'خدمة متكاملة لصياغة خطة عمل احترافية ومقنعة، تشمل دراسات السوق والتوقعات المالية واستراتيجية التسويق. ضرورية لتقديم مشروعك للمستثمرين.'
    },
    price: 7500,
    deliveryTimeDays: 14,
    icon: 'description'
  },
  {
    id: 'serv_2',
    title: { fr: 'Modélisation Financière', ar: 'النمذجة المالية' },
    description: {
      fr: 'Création de modèles financiers détaillés sur 5 ans (compte de résultat, bilan, tableau de flux de trésorerie). Indispensable pour évaluer la viabilité et la rentabilité de votre projet.',
      ar: 'إنشاء نماذج مالية مفصلة على مدى 5 سنوات (بيان الدخل، الميزانية العمومية، بيان التدفقات النقدية). لا غنى عنها لتقييم جدوى وربحية مشروعك.'
    },
    price: 5000,
    deliveryTimeDays: 7,
    icon: 'monitoring'
  },
  {
    id: 'serv_3',
    title: { fr: 'Production de Vidéo Promotionnelle', ar: 'إنتاج فيديو ترويجي' },
    description: {
      fr: 'Réalisation d\'une vidéo de 90 secondes pour présenter votre projet de manière dynamique et engageante. Inclut le script, le tournage (si à Casablanca) et le montage.',
      ar: 'إنتاج فيديو مدته 90 ثانية لتقديم مشروعك بطريقة ديناميكية وجذابة. يشمل كتابة السيناريو والتصوير (إذا كان في الدار البيضاء) والمونتاج.'
    },
    price: 12000,
    deliveryTimeDays: 21,
    icon: 'videocam'
  },
  {
    id: 'serv_4',
    title: { fr: 'Conseil Juridique (Création d\'entreprise)', ar: 'استشارة قانونية (تأسيس شركة)' },
    description: {
      fr: 'Accompagnement par un expert juridique pour le choix de la forme sociale, la rédaction des statuts et l\'immatriculation de votre entreprise au registre de commerce.',
      ar: 'مرافقة من خبير قانوني لاختيار الشكل القانوني للشركة وصياغة النظام الأساسي وتسجيل شركتك في السجل التجاري.'
    },
    price: 4500,
    deliveryTimeDays: 10,
    icon: 'gavel'
  },
  {
    id: 'serv_5',
    title: { fr: 'Stratégie Marketing Digital', ar: 'استراتيجية التسويق الرقمي' },
    description: {
      fr: 'Élaboration d\'une stratégie complète pour le lancement de votre campagne sur les réseaux sociaux et les moteurs de recherche (SEO/SEA).',
      ar: 'تطوير استراتيجية كاملة لإطلاق حملتك على الشبكات الاجتماعية ومحركات البحث (SEO/SEA).'
    },
    price: 6000,
    deliveryTimeDays: 10,
    icon: 'campaign'
  },
  {
    id: 'serv_6',
    title: { fr: 'Création d\'Identité Visuelle', ar: 'تصميم الهوية البصرية' },
    description: {
      fr: 'Conception de votre logo, charte graphique et supports de communication de base (carte de visite, papier à en-tête) pour une image de marque professionnelle.',
      ar: 'تصميم شعارك ودليلك البصري ومواد الاتصال الأساسية (بطاقة العمل، الورق الرسمي) للحصول على صورة علامة تجارية احترافية.'
    },
    price: 8000,
    deliveryTimeDays: 15,
    icon: 'palette'
  },
];

export let mockServiceRequests: ServiceRequest[] = [
  {
    id: 'sreq_1',
    userId: 'usr_po1', // Youssef Alaoui
    serviceId: 'serv_2', // Modélisation Financière
    status: ServiceStatus.COMPLETED,
    requestDate: new Date('2024-04-15'),
    completionDate: new Date('2024-04-22'),
  },
  {
    id: 'sreq_2',
    userId: 'usr_po1',
    serviceId: 'serv_3', // Vidéo
    status: ServiceStatus.IN_PROGRESS,
    requestDate: new Date('2024-06-20'),
  },
  {
    id: 'sreq_3',
    userId: 'usr_po3', // Sofia Tazi
    serviceId: 'serv_1', // Business Plan
    status: ServiceStatus.PENDING,
    requestDate: new Date('2024-07-01'),
  },
];

// WITHDRAWAL REQUESTS
export let mockWithdrawalRequests: WithdrawalRequest[] = [
  {
    id: 'wreq_1',
    userId: 'usr_inv1',
    amount: 5000,
    rib: '123456789012345678901234',
    bankName: 'Attijariwafa Bank',
    status: WithdrawalStatus.PENDING,
    requestDate: new Date('2024-07-20T10:00:00Z'),
  },
  {
    id: 'wreq_2',
    userId: 'usr_po1',
    amount: 15000,
    rib: '987654321098765432109876',
    bankName: 'BMCE Bank',
    status: WithdrawalStatus.COMPLETED,
    requestDate: new Date('2024-07-18T15:30:00Z'),
    decisionDate: new Date('2024-07-19T11:00:00Z'),
  },
  {
    id: 'wreq_3',
    userId: 'usr_inv3',
    amount: 2500,
    rib: '555566667777888899990000',
    bankName: 'CIH Bank',
    status: WithdrawalStatus.REJECTED,
    requestDate: new Date('2024-07-17T09:00:00Z'),
    decisionDate: new Date('2024-07-17T14:00:00Z'),
    adminNotes: 'RIB invalide.',
  },
];